version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./rclone.conf:/app/rclone.conf:ro
      - /tmp:/tmp  # For temporary file handling
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
      # Server configuration for large files
      - SERVER_READ_TIMEOUT=1800s    # 30 minutes for very large files
      - SERVER_WRITE_TIMEOUT=1800s   # 30 minutes for very large files
      - SERVER_IDLE_TIMEOUT=120s     # 2 minutes idle timeout
      - SERVER_ADDR=0.0.0.0:8080
    deploy:
      resources:
        limits:
          memory: 4G    # Increased for large file handling
        reservations:
          memory: 512M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    # Add swap limit for better memory management
    mem_swappiness: 60
    # Increase shm size for better performance
    shm_size: '256mb'